<?php
return [
    "countries" => [
        ["code" => "AFG", "name" => "Afghanistan", "flag" => "afg.svg"],
        ["code" => "ALA", "name" => "Åland Islands", "flag" => "ala.svg"],
        ["code" => "ALB", "name" => "Albania", "flag" => "alb.svg"],
        ["code" => "DZA", "name" => "Algeria", "flag" => "dza.svg"],
        ["code" => "ASM", "name" => "American Samoa", "flag" => "asm.svg"],
        ["code" => "AND", "name" => "Andorra", "flag" => "and.svg"],
        ["code" => "AGO", "name" => "Angola", "flag" => "ago.svg"],
        ["code" => "AIA", "name" => "Anguilla", "flag" => "aia.svg"],
        ["code" => "ATA", "name" => "Antarctica", "flag" => "ata.svg"],
        ["code" => "ATG", "name" => "Antigua and Barbuda", "flag" => "atg.svg"],
        ["code" => "ARG", "name" => "Argentina", "flag" => "arg.svg"],
        ["code" => "ARM", "name" => "Armenia", "flag" => "arm.svg"],
        ["code" => "ABW", "name" => "Aruba", "flag" => "abw.svg"],
        ["code" => "AUS", "name" => "Australia", "flag" => "aus.svg"],
        ["code" => "AUT", "name" => "Austria", "flag" => "aut.svg"],
        ["code" => "AZE", "name" => "Azerbaijan", "flag" => "aze.svg"],
        ["code" => "BHS", "name" => "Bahamas", "flag" => "bhs.svg"],
        ["code" => "BHR", "name" => "Bahrain", "flag" => "bhr.svg"],
        ["code" => "BGD", "name" => "Bangladesh", "flag" => "bgd.svg"],
        ["code" => "BRB", "name" => "Barbados", "flag" => "brb.svg"],
        ["code" => "BLR", "name" => "Belarus", "flag" => "blr.svg"],
        ["code" => "BEL", "name" => "Belgium", "flag" => "bel.svg"],
        ["code" => "BLZ", "name" => "Belize", "flag" => "blz.svg"],
        ["code" => "BEN", "name" => "Benin", "flag" => "ben.svg"],
        ["code" => "BMU", "name" => "Bermuda", "flag" => "bmu.svg"],
        ["code" => "BTN", "name" => "Bhutan", "flag" => "btn.svg"],
        ["code" => "BOL", "name" => "Bolivia (Plurinational State of)", "flag" => "bol.svg"],
        ["code" => "BES", "name" => "Bonaire, Sint Eustatius and Saba", "flag" => "bes.svg"],
        ["code" => "BIH", "name" => "Bosnia and Herzegovina", "flag" => "bih.svg"],
        ["code" => "BWA", "name" => "Botswana", "flag" => "bwa.svg"],
        ["code" => "BVT", "name" => "Bouvet Island", "flag" => "bvt.svg"],
        ["code" => "BRA", "name" => "Brazil", "flag" => "bra.svg"],
        ["code" => "IOT", "name" => "British Indian Ocean Territory", "flag" => "iot.svg"],
        ["code" => "UMI", "name" => "United States Minor Outlying Islands", "flag" => "umi.svg"],
        ["code" => "VGB", "name" => "Virgin Islands (British)", "flag" => "vgb.svg"],
        ["code" => "VIR", "name" => "Virgin Islands (U.S.)", "flag" => "vir.svg"],
        ["code" => "BRN", "name" => "Brunei Darussalam", "flag" => "brn.svg"],
        ["code" => "BGR", "name" => "Bulgaria", "flag" => "bgr.svg"],
        ["code" => "BFA", "name" => "Burkina Faso", "flag" => "bfa.svg"],
        ["code" => "BDI", "name" => "Burundi", "flag" => "bdi.svg"],
        ["code" => "KHM", "name" => "Cambodia", "flag" => "khm.svg"],
        ["code" => "CMR", "name" => "Cameroon", "flag" => "cmr.svg"],
        ["code" => "CAN", "name" => "Canada", "flag" => "can.svg"],
        ["code" => "CPV", "name" => "Cabo Verde", "flag" => "cpv.svg"],
        ["code" => "CYM", "name" => "Cayman Islands", "flag" => "cym.svg"],
        ["code" => "CAF", "name" => "Central African Republic", "flag" => "caf.svg"],
        ["code" => "TCD", "name" => "Chad", "flag" => "tcd.svg"],
        ["code" => "CHL", "name" => "Chile", "flag" => "chl.svg"],
        ["code" => "CHN", "name" => "China", "flag" => "chn.svg"],
        ["code" => "CXR", "name" => "Christmas Island", "flag" => "cxr.svg"],
        ["code" => "CCK", "name" => "Cocos (Keeling) Islands", "flag" => "cck.svg"],
        ["code" => "COL", "name" => "Colombia", "flag" => "col.svg"],
        ["code" => "COM", "name" => "Comoros", "flag" => "com.svg"],
        ["code" => "COG", "name" => "Congo", "flag" => "cog.svg"],
        ["code" => "COD", "name" => "Congo (Democratic Republic of the)", "flag" => "cod.svg"],
        ["code" => "COK", "name" => "Cook Islands", "flag" => "cok.svg"],
        ["code" => "CRI", "name" => "Costa Rica", "flag" => "cri.svg"],
        ["code" => "HRV", "name" => "Croatia", "flag" => "hrv.svg"],
        ["code" => "CUB", "name" => "Cuba", "flag" => "cub.svg"],
        ["code" => "CUW", "name" => "Curaçao", "flag" => "cuw.svg"],
        ["code" => "CYP", "name" => "Cyprus", "flag" => "cyp.svg"],
        ["code" => "CZE", "name" => "Czech Republic", "flag" => "cze.svg"],
        ["code" => "DNK", "name" => "Denmark", "flag" => "dnk.svg"],
        ["code" => "DJI", "name" => "Djibouti", "flag" => "dji.svg"],
        ["code" => "DMA", "name" => "Dominica", "flag" => "dma.svg"],
        ["code" => "DOM", "name" => "Dominican Republic", "flag" => "dom.svg"],
        ["code" => "ECU", "name" => "Ecuador", "flag" => "ecu.svg"],
        ["code" => "EGY", "name" => "Egypt", "flag" => "egy.svg"],
        ["code" => "SLV", "name" => "El Salvador", "flag" => "slv.svg"],
        ["code" => "GNQ", "name" => "Equatorial Guinea", "flag" => "gnq.svg"],
        ["code" => "ERI", "name" => "Eritrea", "flag" => "eri.svg"],
        ["code" => "EST", "name" => "Estonia", "flag" => "est.svg"],
        ["code" => "ETH", "name" => "Ethiopia", "flag" => "eth.svg"],
        ["code" => "FLK", "name" => "Falkland Islands (Malvinas)", "flag" => "flk.svg"],
        ["code" => "FRO", "name" => "Faroe Islands", "flag" => "fro.svg"],
        ["code" => "FJI", "name" => "Fiji", "flag" => "fji.svg"],
        ["code" => "FIN", "name" => "Finland", "flag" => "fin.svg"],
        ["code" => "FRA", "name" => "France", "flag" => "fra.svg"],
        ["code" => "GUF", "name" => "French Guiana", "flag" => "guf.svg"],
        ["code" => "PYF", "name" => "French Polynesia", "flag" => "pyf.svg"],
        ["code" => "ATF", "name" => "French Southern Territories", "flag" => "atf.svg"],
        ["code" => "GAB", "name" => "Gabon", "flag" => "gab.svg"],
        ["code" => "GMB", "name" => "Gambia", "flag" => "gmb.svg"],
        ["code" => "GEO", "name" => "Georgia", "flag" => "geo.svg"],
        ["code" => "DEU", "name" => "Germany", "flag" => "deu.svg"],
        ["code" => "GHA", "name" => "Ghana", "flag" => "gha.svg"],
        ["code" => "GIB", "name" => "Gibraltar", "flag" => "gib.svg"],
        ["code" => "GRC", "name" => "Greece", "flag" => "grc.svg"],
        ["code" => "GRL", "name" => "Greenland", "flag" => "grl.svg"],
        ["code" => "GRD", "name" => "Grenada", "flag" => "grd.svg"],
        ["code" => "GLP", "name" => "Guadeloupe", "flag" => "glp.svg"],
        ["code" => "GUM", "name" => "Guam", "flag" => "gum.svg"],
        ["code" => "GTM", "name" => "Guatemala", "flag" => "gtm.svg"],
        ["code" => "GGY", "name" => "Guernsey", "flag" => "ggy.svg"],
        ["code" => "GIN", "name" => "Guinea", "flag" => "gin.svg"],
        ["code" => "GNB", "name" => "Guinea-Bissau", "flag" => "gnb.svg"],
        ["code" => "GUY", "name" => "Guyana", "flag" => "guy.svg"],
        ["code" => "HTI", "name" => "Haiti", "flag" => "hti.svg"],
        ["code" => "HMD", "name" => "Heard Island and McDonald Islands", "flag" => "hmd.svg"],
        ["code" => "VAT", "name" => "Holy See", "flag" => "vat.svg"],
        ["code" => "HND", "name" => "Honduras", "flag" => "hnd.svg"],
        ["code" => "HKG", "name" => "Hong Kong", "flag" => "hkg.svg"],
        ["code" => "HUN", "name" => "Hungary", "flag" => "hun.svg"],
        ["code" => "ISL", "name" => "Iceland", "flag" => "isl.svg"],
        ["code" => "IND", "name" => "India", "flag" => "ind.svg"],
        ["code" => "IDN", "name" => "Indonesia", "flag" => "idn.svg"],
        ["code" => "CIV", "name" => "Côte d'Ivoire", "flag" => "civ.svg"],
        ["code" => "IRN", "name" => "Iran (Islamic Republic of)", "flag" => "irn.svg"],
        ["code" => "IRQ", "name" => "Iraq", "flag" => "irq.svg"],
        ["code" => "IRL", "name" => "Ireland", "flag" => "irl.svg"],
        ["code" => "IMN", "name" => "Isle of Man", "flag" => "imn.svg"],
        ["code" => "ISR", "name" => "Israel", "flag" => "isr.svg"],
        ["code" => "ITA", "name" => "Italy", "flag" => "ita.svg"],
        ["code" => "JAM", "name" => "Jamaica", "flag" => "jam.svg"],
        ["code" => "JPN", "name" => "Japan", "flag" => "jpn.svg"],
        ["code" => "JEY", "name" => "Jersey", "flag" => "jey.svg"],
        ["code" => "JOR", "name" => "Jordan", "flag" => "jor.svg"],
        ["code" => "KAZ", "name" => "Kazakhstan", "flag" => "kaz.svg"],
        ["code" => "KEN", "name" => "Kenya", "flag" => "ken.svg"],
        ["code" => "KIR", "name" => "Kiribati", "flag" => "kir.svg"],
        ["code" => "KWT", "name" => "Kuwait", "flag" => "kwt.svg"],
        ["code" => "KGZ", "name" => "Kyrgyzstan", "flag" => "kgz.svg"],
        ["code" => "LAO", "name" => "Lao People's Democratic Republic", "flag" => "lao.svg"],
        ["code" => "LVA", "name" => "Latvia", "flag" => "lva.svg"],
        ["code" => "LBN", "name" => "Lebanon", "flag" => "lbn.svg"],
        ["code" => "LSO", "name" => "Lesotho", "flag" => "lso.svg"],
        ["code" => "LBR", "name" => "Liberia", "flag" => "lbr.svg"],
        ["code" => "LBY", "name" => "Libya", "flag" => "lby.svg"],
        ["code" => "LIE", "name" => "Liechtenstein", "flag" => "lie.svg"],
        ["code" => "LTU", "name" => "Lithuania", "flag" => "ltu.svg"],
        ["code" => "LUX", "name" => "Luxembourg", "flag" => "lux.svg"],
        ["code" => "MAC", "name" => "Macao", "flag" => "mac.svg"],
        ["code" => "MKD", "name" => "Macedonia (the former Yugoslav Republic of)", "flag" => "mkd.svg"],
        ["code" => "MDG", "name" => "Madagascar", "flag" => "mdg.svg"],
        ["code" => "MWI", "name" => "Malawi", "flag" => "mwi.svg"],
        ["code" => "MYS", "name" => "Malaysia", "flag" => "mys.svg"],
        ["code" => "MDV", "name" => "Maldives", "flag" => "mdv.svg"],
        ["code" => "MLI", "name" => "Mali", "flag" => "mli.svg"],
        ["code" => "MLT", "name" => "Malta", "flag" => "mlt.svg"],
        ["code" => "MHL", "name" => "Marshall Islands", "flag" => "mhl.svg"],
        ["code" => "MTQ", "name" => "Martinique", "flag" => "mtq.svg"],
        ["code" => "MRT", "name" => "Mauritania", "flag" => "mrt.svg"],
        ["code" => "MUS", "name" => "Mauritius", "flag" => "mus.svg"],
        ["code" => "MYT", "name" => "Mayotte", "flag" => "myt.svg"],
        ["code" => "MEX", "name" => "Mexico", "flag" => "mex.svg"],
        ["code" => "FSM", "name" => "Micronesia (Federated States of)", "flag" => "fsm.svg"],
        ["code" => "MDA", "name" => "Moldova (Republic of)", "flag" => "mda.svg"],
        ["code" => "MCO", "name" => "Monaco", "flag" => "mco.svg"],
        ["code" => "MNG", "name" => "Mongolia", "flag" => "mng.svg"],
        ["code" => "MNE", "name" => "Montenegro", "flag" => "mne.svg"],
        ["code" => "MSR", "name" => "Montserrat", "flag" => "msr.svg"],
        ["code" => "MAR", "name" => "Morocco", "flag" => "mar.svg"],
        ["code" => "MOZ", "name" => "Mozambique", "flag" => "moz.svg"],
        ["code" => "MMR", "name" => "Myanmar", "flag" => "mmr.svg"],
        ["code" => "NAM", "name" => "Namibia", "flag" => "nam.svg"],
        ["code" => "NRU", "name" => "Nauru", "flag" => "nru.svg"],
        ["code" => "NPL", "name" => "Nepal", "flag" => "npl.svg"],
        ["code" => "NLD", "name" => "Netherlands", "flag" => "nld.svg"],
        ["code" => "NCL", "name" => "New Caledonia", "flag" => "ncl.svg"],
        ["code" => "NZL", "name" => "New Zealand", "flag" => "nzl.svg"],
        ["code" => "NIC", "name" => "Nicaragua", "flag" => "nic.svg"],
        ["code" => "NER", "name" => "Niger", "flag" => "ner.svg"],
        ["code" => "NGA", "name" => "Nigeria", "flag" => "nga.svg"],
        ["code" => "NIU", "name" => "Niue", "flag" => "niu.svg"],
        ["code" => "NFK", "name" => "Norfolk Island", "flag" => "nfk.svg"],
        ["code" => "PRK", "name" => "Korea (Democratic People's Republic of)", "flag" => "prk.svg"],
        ["code" => "MNP", "name" => "Northern Mariana Islands", "flag" => "mnp.svg"],
        ["code" => "NOR", "name" => "Norway", "flag" => "nor.svg"],
        ["code" => "OMN", "name" => "Oman", "flag" => "omn.svg"],
        ["code" => "PAK", "name" => "Pakistan", "flag" => "pak.svg"],
        ["code" => "PLW", "name" => "Palau", "flag" => "plw.svg"],
        ["code" => "PSE", "name" => "Palestine, State of", "flag" => "pse.svg"],
        ["code" => "PAN", "name" => "Panama", "flag" => "pan.svg"],
        ["code" => "PNG", "name" => "Papua New Guinea", "flag" => "png.svg"],
        ["code" => "PRY", "name" => "Paraguay", "flag" => "pry.svg"],
        ["code" => "PER", "name" => "Peru", "flag" => "per.svg"],
        ["code" => "PHL", "name" => "Philippines", "flag" => "phl.svg"],
        ["code" => "PCN", "name" => "Pitcairn", "flag" => "pcn.svg"],
        ["code" => "POL", "name" => "Poland", "flag" => "pol.svg"],
        ["code" => "PRT", "name" => "Portugal", "flag" => "prt.svg"],
        ["code" => "PRI", "name" => "Puerto Rico", "flag" => "pri.svg"],
        ["code" => "QAT", "name" => "Qatar", "flag" => "qat.svg"],
        ["code" => "KOS", "name" => "Republic of Kosovo", "flag" => "kos.svg"],
        ["code" => "REU", "name" => "Réunion", "flag" => "reu.svg"],
        ["code" => "ROU", "name" => "Romania", "flag" => "rou.svg"],
        ["code" => "RUS", "name" => "Russian Federation", "flag" => "rus.svg"],
        ["code" => "RWA", "name" => "Rwanda", "flag" => "rwa.svg"],
        ["code" => "BLM", "name" => "Saint Barthélemy", "flag" => "blm.svg"],
        ["code" => "SHN", "name" => "Saint Helena, Ascension and Tristan da Cunha", "flag" => "shn.svg"],
        ["code" => "KNA", "name" => "Saint Kitts and Nevis", "flag" => "kna.svg"],
        ["code" => "LCA", "name" => "Saint Lucia", "flag" => "lca.svg"],
        ["code" => "MAF", "name" => "Saint Martin (French part)", "flag" => "maf.svg"],
        ["code" => "SPM", "name" => "Saint Pierre and Miquelon", "flag" => "spm.svg"],
        ["code" => "VCT", "name" => "Saint Vincent and the Grenadines", "flag" => "vct.svg"],
        ["code" => "WSM", "name" => "Samoa", "flag" => "wsm.svg"],
        ["code" => "SMR", "name" => "San Marino", "flag" => "smr.svg"],
        ["code" => "STP", "name" => "Sao Tome and Principe", "flag" => "stp.svg"],
        ["code" => "SAU", "name" => "Saudi Arabia", "flag" => "sau.svg"],
        ["code" => "SEN", "name" => "Senegal", "flag" => "sen.svg"],
        ["code" => "SRB", "name" => "Serbia", "flag" => "srb.svg"],
        ["code" => "SYC", "name" => "Seychelles", "flag" => "syc.svg"],
        ["code" => "SLE", "name" => "Sierra Leone", "flag" => "sle.svg"],
        ["code" => "SGP", "name" => "Singapore", "flag" => "sgp.svg"],
        ["code" => "SXM", "name" => "Sint Maarten (Dutch part)", "flag" => "sxm.svg"],
        ["code" => "SVK", "name" => "Slovakia", "flag" => "svk.svg"],
        ["code" => "SVN", "name" => "Slovenia", "flag" => "svn.svg"],
        ["code" => "SLB", "name" => "Solomon Islands", "flag" => "slb.svg"],
        ["code" => "SOM", "name" => "Somalia", "flag" => "som.svg"],
        ["code" => "ZAF", "name" => "South Africa", "flag" => "zaf.svg"],
        ["code" => "SGS", "name" => "South Georgia and the South Sandwich Islands", "flag" => "sgs.svg"],
        ["code" => "KOR", "name" => "Korea (Republic of)", "flag" => "kor.svg"],
        ["code" => "SSD", "name" => "South Sudan", "flag" => "ssd.svg"],
        ["code" => "ESP", "name" => "Spain", "flag" => "esp.svg"],
        ["code" => "LKA", "name" => "Sri Lanka", "flag" => "lka.svg"],
        ["code" => "SDN", "name" => "Sudan", "flag" => "sdn.svg"],
        ["code" => "SUR", "name" => "Suriname", "flag" => "sur.svg"],
        ["code" => "SJM", "name" => "Svalbard and Jan Mayen", "flag" => "sjm.svg"],
        ["code" => "SWZ", "name" => "Swaziland", "flag" => "swz.svg"],
        ["code" => "SWE", "name" => "Sweden", "flag" => "swe.svg"],
        ["code" => "CHE", "name" => "Switzerland", "flag" => "che.svg"],
        ["code" => "SYR", "name" => "Syrian Arab Republic", "flag" => "syr.svg"],
        ["code" => "TWN", "name" => "Taiwan", "flag" => "twn.svg"],
        ["code" => "TJK", "name" => "Tajikistan", "flag" => "tjk.svg"],
        ["code" => "TZA", "name" => "Tanzania, United Republic of", "flag" => "tza.svg"],
        ["code" => "THA", "name" => "Thailand", "flag" => "tha.svg"],
        ["code" => "TLS", "name" => "Timor-Leste", "flag" => "tls.svg"],
        ["code" => "TGO", "name" => "Togo", "flag" => "tgo.svg"],
        ["code" => "TKL", "name" => "Tokelau", "flag" => "tkl.svg"],
        ["code" => "TON", "name" => "Tonga", "flag" => "ton.svg"],
        ["code" => "TTO", "name" => "Trinidad and Tobago", "flag" => "tto.svg"],
        ["code" => "TUN", "name" => "Tunisia", "flag" => "tun.svg"],
        ["code" => "TUR", "name" => "Turkey", "flag" => "tur.svg"],
        ["code" => "TKM", "name" => "Turkmenistan", "flag" => "tkm.svg"],
        ["code" => "TCA", "name" => "Turks and Caicos Islands", "flag" => "tca.svg"],
        ["code" => "TUV", "name" => "Tuvalu", "flag" => "tuv.svg"],
        ["code" => "UGA", "name" => "Uganda", "flag" => "uga.svg"],
        ["code" => "UKR", "name" => "Ukraine", "flag" => "ukr.svg"],
        ["code" => "UAE", "name" => "United Arab Emirates", "flag" => "are.svg"],
        ["code" => "GBR", "name" => "United Kingdom of Great Britain and Northern Ireland", "flag" => "gbr.svg"],
        ["code" => "USA", "name" => "United States of America", "flag" => "usa.svg"],
        ["code" => "URY", "name" => "Uruguay", "flag" => "ury.svg"],
        ["code" => "UZB", "name" => "Uzbekistan", "flag" => "uzb.svg"],
        ["code" => "VUT", "name" => "Vanuatu", "flag" => "vut.svg"],
        ["code" => "VEN", "name" => "Venezuela (Bolivarian Republic of)", "flag" => "ven.svg"],
        ["code" => "VNM", "name" => "Viet Nam", "flag" => "vnm.svg"],
        ["code" => "WLF", "name" => "Wallis and Futuna", "flag" => "wlf.svg"],
        ["code" => "ESH", "name" => "Western Sahara", "flag" => "esh.svg"],
        ["code" => "YEM", "name" => "Yemen", "flag" => "yem.svg"],
        ["code" => "ZMB", "name" => "Zambia", "flag" => "zmb.svg"],
        ["code" => "ZWE", "name" => "Zimbabwe", "flag" => "zwe.svg"],
    ]

];
